
version: "3"
networks:
    default:
      driver: bridge
      ipam:
        config:
        - subnet:  192.168.185.0/24

services:
    web:
        build:
            context: .
            args:
                MIBEW_VERSION: 3.5.7
                MIBEW_SHA1: 48393d8fb15aa176d1216aef2a2a6b5797488fdc2269cf10d07cd11e38d09718
                MIBEW_DE_SHA1: 5f9c6053560b72a3f06d626a6bd83af9a2cce37e
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        volumes:
            - ./mibew-config/config.yml:/var/www/html/mibew/configs/config.yml
            - ./mibew-config/styles:/var/www/html/mibew/styles
            - ./mibew-config/sounds:/var/www/html/mibew/sounds
            - ./mibew-config/plugins:/var/www/html/mibew/plugins
            - ./mibew-config/locales:/var/www/html/mibew/locales
    cron:
        depends_on:
            - db
        build:
            context: cron/
    db:
        image: mysql:8
        restart: always
        platform: linux/x86_64
        volumes:
            - ./db_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=mibew
            - MYSQL_USER=mibew
            - MYSQL_PASSWORD=mibew
